### PR TITLE
Updated atp-view.coffee

### PR DESCRIPTION
**Pull request by jeremyramin**
moveToCurrentDirectory in atp-view.coffee was not working on my mac so
I found the culprit and wrote fixed the script. I’m assuming that it
will work universally now but I could be mistaken. Someone will need to
test it on Windows.

The problem was the regex in the getCurrentFileName not matching the
file path correctly. Fixed it by getting the file object from the
activeTextEditor and grabbing the base name. Works properly now on my Mac.

This is my first pull request, so I'm sorry if I'm did something wrong. I'm hoping this helps.

### CODE REVIEW

**Comment by IrksomeZeus** [comment]
Possibly has something to do with issue #53...

**Comment by jeremyramin** [comment]
I just had a chance to test this and you are right, it does not work on Mac either. Interestingly enough, %(editor.path) and %(editor.file) work just fine. I'll take a look and see if I can fix it.

**Comment by jeremyramin** [comment]
6cebf06958dfb3deb3185901749011bf56ba9ee1 should fix isis97/atom-terminal-panel#54 and fix isis97/atom-terminal-panel#53

**Comment by IrksomeZeus** [comment]
:+1: Awesome work! I just went through and tested those changes and they all seem to work on my computer... maybe one day this will get merged :smiley:

**Pull request merged**
